export type RootStackParamList = {
  Home: undefined;
  Login: undefined;
  Courses: undefined;
  Assignment: undefined;
  Assignment1: undefined;
  SingleCorrect: undefined;
  AddQuestion: undefined;
  Chapters: undefined;
  AddVideo: undefined;
  ActiveCourses: undefined;
  Forum: undefined;
  Post: undefined;
  SelectedCourse: undefined;
  Tags: undefined;
  Tests: undefined;
  Analytics: undefined;
  Video: undefined;
  Testscreen: undefined;
  Browsescreen: undefined;
  VideoComponent: undefined;
  SubmitAssignement: undefined;
  More: undefined;
  SelectCategory: undefined;
  Assignments: undefined;
  Notes: undefined;
  Videos: undefined;
};
